# Generated by Django 5.2.18 on 2026-10-06 18:00

import django.core.validators
import django.db.models.deletion
import uuid
import wall.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Nombre')),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video MP4'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to=wall.models.asset_path)),
                ('content_type', models.CharField(max_length=80)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('draft_revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(related_name='publications', to='wall.asset')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wall.publication')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Somos Telecable', max_length=80, verbose_name='Nombre del muro')),
                ('welcome_title', models.CharField(default='La conexión más importante somos nosotros.', max_length=100, verbose_name='Titular de bienvenida')),
                ('welcome_body', models.CharField(default='Historias y momentos que nos acercan.', max_length=180, verbose_name='Texto de bienvenida')),
                ('ticker', models.CharField(default='Conectando oportunidades.', max_length=220, verbose_name='Mensaje inferior')),
                ('interval_minutes', models.PositiveSmallIntegerField(choices=[(1, '1 minuto'), (5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos')], default=15, verbose_name='Minutos de muro entre videos')),
                ('videos_per_turn', models.CharField(choices=[('one', 'Un video'), ('all', 'Toda la lista')], default='all', max_length=5, verbose_name='Videos por turno')),
                ('quiz_enabled', models.BooleanField(default=True, verbose_name='Mostrar reto de palabras')),
                ('qr_enabled', models.BooleanField(default=True, verbose_name='Mostrar QR de Telecable')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('current_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wall.publication')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wall.asset', verbose_name='Música de fondo')),
            ],
            options={
                'permissions': [('edit_wall', 'Editar contenido del muro'), ('publish_wall', 'Publicar y recuperar versiones del muro'), ('manage_displays', 'Administrar enlaces de pantallas')],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='wall.wall'),
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la pantalla')),
                ('token', models.CharField(default=wall.models.display_token, editable=False, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Acceso habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='wall.wall')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Imagen / anuncio'), ('video', 'Video'), ('message', 'Mensaje'), ('event', 'Evento'), ('recognition', 'Reconocimiento')], max_length=16, verbose_name='Tipo de contenido')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('body', models.CharField(blank=True, max_length=250, verbose_name='Texto de apoyo')),
                ('event_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del evento')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lugar del evento')),
                ('duration_seconds', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(120)], verbose_name='Segundos por imagen o mensaje')),
                ('sort_order', models.PositiveSmallIntegerField(default=10, verbose_name='Orden (menor aparece primero)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Incluir al publicar')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Mostrar desde')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Retirar el')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wall.asset', verbose_name='Archivo')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='wall.wall')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('department', models.CharField(blank=True, max_length=80, verbose_name='Área')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Mes')),
                ('enabled', models.BooleanField(default=True, verbose_name='Incluir al publicar')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthdays', to='wall.wall')),
            ],
            options={
                'ordering': ['month', 'day', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('wall', 'number'), name='unique_wall_publication'),
        ),
    ]
