# Generated by Django 5.2.18 on 2026-10-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='greeting',
            field=models.CharField(blank=True, max_length=180, verbose_name='Dedicatoria'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birthdays', to='wall.asset', verbose_name='Foto'),
        ),
    ]
